--- Makefile	2013-03-14 00:47:01.729051746 +0400
+++ Makefile.l2tp_ppp	2013-03-14 00:47:01.725051746 +0400
@@ -3,6 +3,7 @@
 #
 
 obj-$(CONFIG_L2TP) += l2tp_core.o
+obj-$(CONFIG_L2TP) += l2tp_ppp.o
 
 # Build l2tp as modules if L2TP is M
 obj-$(subst y,$(CONFIG_L2TP),$(CONFIG_PPPOL2TP)) += l2tp_ppp.o
