#!/bin/bash

###
# Configure routing table for Corbina (Beeline) ISP

# Information available at project homepage:
# http://www.candyboxrouter.org

# Maintainer: Alexander Bykov <alardus@alardus.org>
###


#Looking for default GW
GW=`ip route show default | head -n1 | awk '{print $3}'`

route del default 
route add default gw $GW 
