#!/bin/bash

# Looking for running cava and try to restart it
pid=`/bin/ps -e f | /bin/grep [c]ava.py | /usr/bin/awk '{print $1}'`
kill -9 $pid
/usr/bin/cava.sh

# Installing new kernel modules
rmmod l2tp_core
rmmod l2tp_ppp

depmod -a 
modprobe l2tp_core
modprobe l2tp_ppp
