--- xl2tpd-1.3.1+dfsg.orig/Makefile	2011-10-06 23:22:05.000000000 +0400
+++ Makefile	2013-03-19 10:09:44.459565333 +0400
@@ -62,7 +62,7 @@
 # are packages seperately (eg kernel-headers on Fedora)
 # Note: 2.6.23+ support still needs some changes in the xl2tpd source
 #
-#OSFLAGS+= -DUSE_KERNEL
+OSFLAGS+= -DUSE_KERNEL
 #
 #
 # Uncomment the next line for FreeBSD
